In [1]:
import torch

In [40]:
x = torch.randn(3, requires_grad=True)

In [61]:
x

tensor([-1.3212,  0.5888, -0.8007], requires_grad=True)

In [62]:
y = x + 2
y

tensor([0.6788, 2.5888, 1.1993], grad_fn=<AddBackward0>)

In [42]:
print(x)
print(y)
print(y.grad_fn)

tensor([-1.3212,  0.5888, -0.8007], requires_grad=True)
tensor([0.6788, 2.5888, 1.1993], grad_fn=<AddBackward0>)


In [43]:
z = y * y * 3

In [64]:
y * y * 3

tensor([ 1.3825, 20.1060,  4.3151], grad_fn=<MulBackward0>)

In [59]:
y * y

tensor([0.4608, 6.7020, 1.4384], grad_fn=<MulBackward0>)

In [44]:
z2 = z.mean()

In [45]:
z = z.mean()

In [47]:
print(x.grad)
z.backward()
print(x.grad)

None
tensor([1.3577, 5.1776, 2.3986])


In [58]:
x

tensor([-1.3212,  0.5888, -0.8007], requires_grad=True)

This last line is dz/dx, where z(x) = mean(3 * ((x + 2)^2)). We can check this gave us the right answer: dz/dx is just 
\begin{align*}
    \nabla_x z &= \nabla_x \frac{3 * [(x_1 + 2)^2 + (x_2 + 2)^2 + (x_3 + 2)^2]}{3} \\ 
    &= \nabla_x  [(x_1 + 2)^2 + (x_2 + 2)^2 + (x_3 + 2)^2] \\ 
    &= (x_1 + 2, x_2 + 2, x_3 + 2) \\ 
    &= x + (2, 2, 2).
\end{align*}
Now, with the values of $x$ initialized above, this is
$$
\nabla_x z = (-1.3 + 2, 0.6 + 2, -0.8 + 2) = (0.7, 0.8, -0.6).
$$

In [56]:
a = torch.ones(3)
b = torch.tensor([1, 4, 10])

In [57]:
a * b

tensor([ 1.,  4., 10.])